version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: kaow-postgres-db
    restart: always
    environment:
      POSTGRES_USER: kaowuser
      POSTGRES_PASSWORD: kaowpassword
      POSTGRES_DB: kaowdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - kaow-network

  kaow-api:
    build:
      context: ./KAOW  # <- Ajuste aqui se sua API está em subpasta
      dockerfile: Dockerfile
    container_name: kaow-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=kaowdb;Username=kaowuser;Password=kaowpassword
    networks:
      - kaow-network

volumes:
  postgres-data:

networks:
  kaow-network:
    name: kaow-network
    driver: bridge
